liip_imagine:
  driver: "gd"
  filter_sets:
    my_thumb:
      quality: 75
      filters:
        thumbnail: { size: [120, 90], mode: outbound }
    product_cat:
      quality: 75
      filters:
        thumbnail: { size: [550, 750], mode: outbound }
    product_small:
      quality: 75
      filters:
        thumbnail: { size: [115, 140], mode: outbound }

