#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"
# app/config/routing.yml
_liip_imagine:
  resource: "@LiipImagineBundle/Resources/config/routing.yaml"
